// Code generated by goctl. DO NOT EDIT.
// Source: media.proto

package media

import (
	"context"

	"doushen_by_liujun/service/media/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddChatMessageReq      = pb.AddChatMessageReq
	AddChatMessageResp     = pb.AddChatMessageResp
	ChatMessage            = pb.ChatMessage
	DelChatMessageReq      = pb.DelChatMessageReq
	DelChatMessageResp     = pb.DelChatMessageResp
	GetChatMessageByIdReq  = pb.GetChatMessageByIdReq
	GetChatMessageByIdResp = pb.GetChatMessageByIdResp
	SearchChatMessageReq   = pb.SearchChatMessageReq
	SearchChatMessageResp  = pb.SearchChatMessageResp
	UpdateChatMessageReq   = pb.UpdateChatMessageReq
	UpdateChatMessageResp  = pb.UpdateChatMessageResp

	Media interface {
		// -----------------------鑱婂ぉ淇℃伅-----------------------
		AddChatMessage(ctx context.Context, in *AddChatMessageReq, opts ...grpc.CallOption) (*AddChatMessageResp, error)
		UpdateChatMessage(ctx context.Context, in *UpdateChatMessageReq, opts ...grpc.CallOption) (*UpdateChatMessageResp, error)
		DelChatMessage(ctx context.Context, in *DelChatMessageReq, opts ...grpc.CallOption) (*DelChatMessageResp, error)
		GetChatMessageById(ctx context.Context, in *GetChatMessageByIdReq, opts ...grpc.CallOption) (*GetChatMessageByIdResp, error)
		SearchChatMessage(ctx context.Context, in *SearchChatMessageReq, opts ...grpc.CallOption) (*SearchChatMessageResp, error)
	}

	defaultMedia struct {
		cli zrpc.Client
	}
)

func NewMedia(cli zrpc.Client) Media {
	return &defaultMedia{
		cli: cli,
	}
}

// -----------------------鑱婂ぉ淇℃伅-----------------------
func (m *defaultMedia) AddChatMessage(ctx context.Context, in *AddChatMessageReq, opts ...grpc.CallOption) (*AddChatMessageResp, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.AddChatMessage(ctx, in, opts...)
}

func (m *defaultMedia) UpdateChatMessage(ctx context.Context, in *UpdateChatMessageReq, opts ...grpc.CallOption) (*UpdateChatMessageResp, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.UpdateChatMessage(ctx, in, opts...)
}

func (m *defaultMedia) DelChatMessage(ctx context.Context, in *DelChatMessageReq, opts ...grpc.CallOption) (*DelChatMessageResp, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.DelChatMessage(ctx, in, opts...)
}

func (m *defaultMedia) GetChatMessageById(ctx context.Context, in *GetChatMessageByIdReq, opts ...grpc.CallOption) (*GetChatMessageByIdResp, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.GetChatMessageById(ctx, in, opts...)
}

func (m *defaultMedia) SearchChatMessage(ctx context.Context, in *SearchChatMessageReq, opts ...grpc.CallOption) (*SearchChatMessageResp, error) {
	client := pb.NewMediaClient(m.cli.Conn())
	return client.SearchChatMessage(ctx, in, opts...)
}
