// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"doushen_by_liujun/service/chat/rpc/internal/logic"
	"doushen_by_liujun/service/chat/rpc/internal/svc"
	"doushen_by_liujun/service/chat/rpc/pb"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

// -----------------------鑱婂ぉ淇℃伅-----------------------
func (s *ChatServer) AddChatMessage(ctx context.Context, in *pb.AddChatMessageReq) (*pb.AddChatMessageResp, error) {
	l := logic.NewAddChatMessageLogic(ctx, s.svcCtx)
	return l.AddChatMessage(in)
}

func (s *ChatServer) UpdateChatMessage(ctx context.Context, in *pb.UpdateChatMessageReq) (*pb.UpdateChatMessageResp, error) {
	l := logic.NewUpdateChatMessageLogic(ctx, s.svcCtx)
	return l.UpdateChatMessage(in)
}

func (s *ChatServer) DelChatMessage(ctx context.Context, in *pb.DelChatMessageReq) (*pb.DelChatMessageResp, error) {
	l := logic.NewDelChatMessageLogic(ctx, s.svcCtx)
	return l.DelChatMessage(in)
}

func (s *ChatServer) GetChatMessageById(ctx context.Context, in *pb.GetChatMessageByIdReq) (*pb.GetChatMessageByIdResp, error) {
	l := logic.NewGetChatMessageByIdLogic(ctx, s.svcCtx)
	return l.GetChatMessageById(in)
}

func (s *ChatServer) SearchChatMessage(ctx context.Context, in *pb.SearchChatMessageReq) (*pb.SearchChatMessageResp, error) {
	l := logic.NewSearchChatMessageLogic(ctx, s.svcCtx)
	return l.SearchChatMessage(in)
}
