// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package server

import (
	"context"

	"doushen_by_liujun/service/chat/rpc/internal/logic"
	"doushen_by_liujun/service/chat/rpc/internal/svc"
	"doushen_by_liujun/service/chat/rpc/pb"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) AddChatMessage(ctx context.Context, in *pb.AddChatMessageReq) (*pb.AddChatMessageResp, error) {
	l := logic.NewAddChatMessageLogic(ctx, s.svcCtx)
	return l.AddChatMessage(in)
}

func (s *ChatServer) GetChatMessageById(ctx context.Context, in *pb.GetChatMessageByIdReq) (*pb.GetChatMessageByIdResp, error) {
	l := logic.NewGetChatMessageByIdLogic(ctx, s.svcCtx)
	return l.GetChatMessageById(in)
}
