// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"doushen_by_liujun/service/media/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: uploadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/publish"),
	)
}
