// Code generated by goctl. DO NOT EDIT.
// Source: chat.proto

package chat

import (
	"context"

	"doushen_by_liujun/service/chat/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddChatMessageReq      = pb.AddChatMessageReq
	AddChatMessageResp     = pb.AddChatMessageResp
	ChatMessage            = pb.ChatMessage
	DelChatMessageReq      = pb.DelChatMessageReq
	DelChatMessageResp     = pb.DelChatMessageResp
	GetChatMessageByIdReq  = pb.GetChatMessageByIdReq
	GetChatMessageByIdResp = pb.GetChatMessageByIdResp
	SearchChatMessageReq   = pb.SearchChatMessageReq
	SearchChatMessageResp  = pb.SearchChatMessageResp
	UpdateChatMessageReq   = pb.UpdateChatMessageReq
	UpdateChatMessageResp  = pb.UpdateChatMessageResp

	Chat interface {
		// -----------------------鑱婂ぉ淇℃伅-----------------------
		AddChatMessage(ctx context.Context, in *AddChatMessageReq, opts ...grpc.CallOption) (*AddChatMessageResp, error)
		UpdateChatMessage(ctx context.Context, in *UpdateChatMessageReq, opts ...grpc.CallOption) (*UpdateChatMessageResp, error)
		DelChatMessage(ctx context.Context, in *DelChatMessageReq, opts ...grpc.CallOption) (*DelChatMessageResp, error)
		GetChatMessageById(ctx context.Context, in *GetChatMessageByIdReq, opts ...grpc.CallOption) (*GetChatMessageByIdResp, error)
		SearchChatMessage(ctx context.Context, in *SearchChatMessageReq, opts ...grpc.CallOption) (*SearchChatMessageResp, error)
	}

	defaultChat struct {
		cli zrpc.Client
	}
)

func NewChat(cli zrpc.Client) Chat {
	return &defaultChat{
		cli: cli,
	}
}


func (m *defaultChat) AddChatMessage(ctx context.Context, in *AddChatMessageReq, opts ...grpc.CallOption) (*AddChatMessageResp, error) {
	client := pb.NewChatClient(m.cli.Conn())
	return client.AddChatMessage(ctx, in, opts...)
}

func (m *defaultChat) UpdateChatMessage(ctx context.Context, in *UpdateChatMessageReq, opts ...grpc.CallOption) (*UpdateChatMessageResp, error) {
	client := pb.NewChatClient(m.cli.Conn())
	return client.UpdateChatMessage(ctx, in, opts...)
}

func (m *defaultChat) DelChatMessage(ctx context.Context, in *DelChatMessageReq, opts ...grpc.CallOption) (*DelChatMessageResp, error) {
	client := pb.NewChatClient(m.cli.Conn())
	return client.DelChatMessage(ctx, in, opts...)
}

func (m *defaultChat) GetChatMessageById(ctx context.Context, in *GetChatMessageByIdReq, opts ...grpc.CallOption) (*GetChatMessageByIdResp, error) {
	client := pb.NewChatClient(m.cli.Conn())
	return client.GetChatMessageById(ctx, in, opts...)
}

func (m *defaultChat) SearchChatMessage(ctx context.Context, in *SearchChatMessageReq, opts ...grpc.CallOption) (*SearchChatMessageResp, error) {
	client := pb.NewChatClient(m.cli.Conn())
	return client.SearchChatMessage(ctx, in, opts...)
}
