// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"doushen_by_liujun/service/user/rpc/internal/logic"
	"doushen_by_liujun/service/user/rpc/internal/svc"
	"doushen_by_liujun/service/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) AddFollows(ctx context.Context, in *pb.AddFollowsReq) (*pb.AddFollowsResp, error) {
	l := logic.NewAddFollowsLogic(ctx, s.svcCtx)
	return l.AddFollows(in)
}

func (s *UserServer) DelFollows(ctx context.Context, in *pb.DelFollowsReq) (*pb.DelFollowsResp, error) {
	l := logic.NewDelFollowsLogic(ctx, s.svcCtx)
	return l.DelFollows(in)
}

func (s *UserServer) GetFollowsById(ctx context.Context, in *pb.GetFollowsByIdReq) (*pb.GetFollowsByIdResp, error) {
	l := logic.NewGetFollowsByIdLogic(ctx, s.svcCtx)
	return l.GetFollowsById(in)
}

func (s *UserServer) SaveUser(ctx context.Context, in *pb.SaveUserReq) (*pb.SaveUserResp, error) {
	l := logic.NewSaveUserLogic(ctx, s.svcCtx)
	return l.SaveUser(in)
}

func (s *UserServer) CheckUser(ctx context.Context, in *pb.CheckUserReq) (*pb.CheckUserResp, error) {
	l := logic.NewCheckUserLogic(ctx, s.svcCtx)
	return l.CheckUser(in)
}

func (s *UserServer) GetPasswordByUsername(ctx context.Context, in *pb.GetPasswordByUsernameReq) (*pb.GetPasswordByUsernameResp, error) {
	l := logic.NewGetPasswordByUsernameLogic(ctx, s.svcCtx)
	return l.GetPasswordByUsername(in)
}

func (s *UserServer) GetUserinfoById(ctx context.Context, in *pb.GetUserinfoByIdReq) (*pb.GetUserinfoByIdResp, error) {
	l := logic.NewGetUserinfoByIdLogic(ctx, s.svcCtx)
	return l.GetUserinfoById(in)
}

func (s *UserServer) GetUsersByIds(ctx context.Context, in *pb.GetUsersByIdsReq) (*pb.GetUsersByIdsResp, error) {
	l := logic.NewGetUsersByIdsLogic(ctx, s.svcCtx)
	return l.GetUsersByIds(in)
}

func (s *UserServer) GetFollowersById(ctx context.Context, in *pb.GetFollowersByIdReq) (*pb.GetFollowersByIdResp, error) {
	l := logic.NewGetFollowersByIdLogic(ctx, s.svcCtx)
	return l.GetFollowersById(in)
}

func (s *UserServer) GetFollowersCountById(ctx context.Context, in *pb.GetFollowersCountByIdReq) (*pb.GetFollowersCountByIdResp, error) {
	l := logic.NewGetFollowersCountByIdLogic(ctx, s.svcCtx)
	return l.GetFollowersCountById(in)
}

func (s *UserServer) CheckIsFollow(ctx context.Context, in *pb.CheckIsFollowReq) (*pb.CheckIsFollowResp, error) {
	l := logic.NewCheckIsFollowLogic(ctx, s.svcCtx)
	return l.CheckIsFollow(in)
}

func (s *UserServer) GetFriendsById(ctx context.Context, in *pb.GetFriendsByIdReq) (*pb.GetFriendsByIdResp, error) {
	l := logic.NewGetFriendsByIdLogic(ctx, s.svcCtx)
	return l.GetFriendsById(in)
}

func (s *UserServer) GetUserById(ctx context.Context, in *pb.GetUserByIdReq) (*pb.GetUserByIdResp, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserServer) GetUserListByIdList(ctx context.Context, in *pb.GetUserListByIdListReq) (*pb.GetUserListByIdListResp, error) {
	l := logic.NewGetUserListByIdListLogic(ctx, s.svcCtx)
	return l.GetUserListByIdList(in)
}
