version: '3.8'

services:
  redis-master:
    container_name: redis-master
    image: redis:7.0.11-alpine
    hostname: redis-master
    restart: unless-stopped
    ports:
      - "8093:8093"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '3'
    volumes:
      - redis-master:/data
    command:
      - redis-server
      - --bind
      - "0.0.0.0"
      - --port
      - "8093"
      - --requirepass
      - "liujun"
      - --appendonly
      - "yes"
      - --masterauth
      - "liujun"
      - --replica-announce-ip
      - 127.0.0.1
      - --replica-announce-port
      - "8093"

  redis-slave1:
    container_name: redis-slave1
    image: redis:7.0.11-alpine
    hostname: redis-slave1
    restart: unless-stopped
    ports:
      - "8094:8094"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '3'
    volumes:
      - redis-slave1:/data
    command:
      - redis-server
      - --bind
      - "0.0.0.0"
      - --port
      - "8094"
      - --requirepass
      - "liujun"
      - --appendonly
      - "yes"
      - --masterauth
      - "liujun"
      - --replicaof
      - "redis-master 8093"
      - --replica-announce-ip
      - 127.0.0.1
      - --replica-announce-port
      - "8094"

  redis-slave2:
    container_name: redis-slave2
    image: redis:7.0.11-alpine
    hostname: redis-slave2
    restart: unless-stopped
    ports:
      - "8095:8095"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '3'
    volumes:
      - redis-slave2:/data
    command:
      - redis-server
      - --bind
      - "0.0.0.0"
      - --port
      - "8095"
      - --requirepass
      - "liujun"
      - --appendonly
      - "yes"
      - --masterauth
      - "liujun"
      - --replicaof
      - "redis-master 8093"
      - --replica-announce-ip
      - 127.0.0.1
      - --replica-announce-port
      - "8095"

volumes:
  redis-master:
  redis-slave1:
  redis-slave2:

