version: '3'

services:

  #etcd容器 - Etcd container
  etcd:
    image: bitnami/etcd:3.4.27
    container_name: etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:8090
    ports:
      - 8090:2379
    restart: always
    networks:
      - liujun_net

  #prometheus监控 — Prometheus for monitoring
  prometheus:
    image: bitnami/prometheus:2.46.0
    container_name: prometheus
    restart: always
    user: root
    ports:
      - 8091:9090
    networks:
      - liujun_net

  #查看prometheus监控数据 - Grafana to view Prometheus monitoring data
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    hostname: grafana
    user: root
    restart: always
    ports:
      - 8092:3000
    networks:
      - liujun_net
    depends_on:
      - prometheus


  #消息队列 - Message queue
  kafka:
    image: bitnami/kafka:3.3.2
    container_name: kafka
    ports:
      - 8093:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    restart: always
    privileged: true
    user: '1001'
    networks:
      - liujun_net

  #redis容器 - Redis container
  redis:
    image: redis:7.2-rc
    container_name: redis
    ports:
      - 8094:6379
    command: "redis-server --requirepass liujun  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - liujun_net

networks:
  liujun_net:
    driver: bridge

