// Code generated by goctl. DO NOT EDIT.
package types

type UploadReq struct {
	Token string `form:"token"`  // 用户鉴权token
	Title string `form:"title"`  // 视频标题
	Data  []byte `header:"data"` // 视频数据
}

type UploadResp struct {
	StatusCode int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	StatusMsg  string `json:"status_msg"`  // 返回状态描述
}
