// Code generated by goctl. DO NOT EDIT.
// Source: media.proto

package server

import (
	"context"

	"doushen_by_liujun/service/media/rpc/internal/logic"
	"doushen_by_liujun/service/media/rpc/internal/svc"
	"doushen_by_liujun/service/media/rpc/pb"
)

type MediaServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMediaServer
}

func NewMediaServer(svcCtx *svc.ServiceContext) *MediaServer {
	return &MediaServer{
		svcCtx: svcCtx,
	}
}

func (s *MediaServer) SaveVideo(ctx context.Context, in *pb.SaveVideoReq) (*pb.SaveVideoResp, error) {
	l := logic.NewSaveVideoLogic(ctx, s.svcCtx)
	return l.SaveVideo(in)
}
