// Code generated by goctl. DO NOT EDIT.

package model_cache_true

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followsFieldNames          = builder.RawFieldNames(&Follows{})
	followsRows                = strings.Join(followsFieldNames, ",")
	followsRowsExpectAutoSet   = strings.Join(stringx.Remove(followsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followsRowsWithPlaceHolder = strings.Join(stringx.Remove(followsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	followsModel interface {
		Insert(ctx context.Context, data *Follows) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Follows, error)
		Update(ctx context.Context, data *Follows) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFollowsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Follows struct {
		Id         int64          `db:"id"`          // 主键
		UserId     sql.NullString `db:"user_id"`     // 关注的人
		FollowId   sql.NullString `db:"follow_id"`   // 被关注的人
		CreateTime time.Time      `db:"create_time"` // 该条记录创建时间
		UpdateTime time.Time      `db:"update_time"` // 该条最后一次更新时间
		IsDelete   int64          `db:"is_delete"`   // 逻辑删除
	}
)

func newFollowsModel(conn sqlx.SqlConn) *defaultFollowsModel {
	return &defaultFollowsModel{
		conn:  conn,
		table: "`follows`",
	}
}

func (m *defaultFollowsModel) withSession(session sqlx.Session) *defaultFollowsModel {
	return &defaultFollowsModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`follows`",
	}
}

func (m *defaultFollowsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFollowsModel) FindOne(ctx context.Context, id int64) (*Follows, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followsRows, m.table)
	var resp Follows
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowsModel) Insert(ctx context.Context, data *Follows) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, followsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.FollowId, data.IsDelete)
	return ret, err
}

func (m *defaultFollowsModel) Update(ctx context.Context, data *Follows) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FollowId, data.IsDelete, data.Id)
	return err
}

func (m *defaultFollowsModel) tableName() string {
	return m.table
}
